version: '3'
services:
    # Main massassi DB
    db:
        image: postgres:14.1-alpine
        restart: always
        expose:
            - 5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
            POSTGRES_HOST_AUTH_METHOD: scram-sha-256
        volumes:
            - massassi-postgres-data:/var/lib/postgresql/data

    # Main web server; dispatches requests to the various apps based on 
    # hostname/filename/etc.
    web:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./massassi-etc/:/app/massassi-etc/:ro

    # Static parts of massassi, including:
    #  - static/ (stuff required by the entire site like css and main images)
    #  - media/ (user-generated content like levels, screenshots, etc.)
    #  - etc/ (history and brian stuff mounted on a volume)
    #  - the tutorials and other pages generated by the static site generator
    massassi-static:
        image: nginx:latest
        hostname: massassi-static
        restart: always
        expose:
            - 8001
        volumes:
            - django-static:/jedibird-static:ro
            - ./massassi-static/output:/app:ro
            - ./massassi-static/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - massassi-user-data:/massassi-user-data:ro

    # Dynamic parts of massassi, written in python/django and served by 
    # gunicorn
    massassi-django:
        hostname: massassi-django
        build:
            context: ./massassi-django
        restart: always
        expose:
            - 8000
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            MASSASSI_DATABASE_PASSWORD: ${MASSASSI_DATABASE_PASSWORD}
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
            MASSASSI_DATABASE_HOST: ${MASSASSI_DATABASE_HOST}
            SENDGRID_API_KEY: ${SENDGRID_API_KEY}
        volumes:
            - django-static:/jedibird-static:rw
            - massassi-user-data:/massassi-user-data:rw
            - ./import:/home/brian/code/massassi-django/import

    tacc-db:
        image: mysql:8
        hostname: tacc-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${TACC_MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${TACC_MYSQL_DATABASE}
            MYSQL_USER: ${TACC_MYSQL_USER}
            MYSQL_PASSWORD: ${TACC_MYSQL_PASSWORD}
        volumes:
            - ./tacc-db/initial-data:/docker-entrypoint-initdb.d:ro
            - tacc-mysql-data:/var/lib/mysql

    tacc-web:
        hostname: tacc-web
        build:
            context: ./tacc-web
        restart: always
        ports:
            - "9000:9000"
        environment:
            MYSQL_HOST: tacc-db
            MYSQL_DATABASE: ${TACC_MYSQL_DATABASE}
            MYSQL_USER: ${TACC_MYSQL_USER}
            MYSQL_PASSWORD: ${TACC_MYSQL_PASSWORD}

    rbots-web:
        hostname: rbots-web
        build:
            context: ./rbots-web
        restart: always
        ports:
            - "9001:9001"

volumes:
    massassi-postgres-data:
    massassi-user-data:
    django-static:
    tacc-mysql-data:
