version: '3'
services:
    # Only in prod we send host-gateway, it's used by certbot
    web:
        volumes:
            - ./massassi-web/nginx-local.conf:/etc/nginx/conf.d/default.conf

    massassi-django:
        command: "gunicorn --reload --chdir /app/massassi-django/massassi-django massassi.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - ./massassi-django:/app/massassi-django/massassi-django
