version: '3'
services:
    # Main massassi DB
    db:
        image: postgres:14.1-alpine
        restart: always
        expose:
            - 5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
            POSTGRES_HOST_AUTH_METHOD: scram-sha-256
        volumes:
            - massassi-postgres-data:/var/lib/postgresql/data

    # This is a mysql instance that gets pre-loaded with the sql file in:
    #
    # massassi-mysql-import/docker-entrypoint-initdb.d
    #
    # This holds existing/current mysql data used during data import.  Once the 
    # site is completely moved over and live, this mysql instance and data can 
    # be completely removed.
    db-import:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./massassi-mysql-import/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

    # Main web server; dispatches requests to the various apps based on 
    # hostname/filename/etc.
    web:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./massassi-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./massassi-etc/:/app/massassi-etc/:ro

    # Static parts of massassi, including:
    #  - static/ (stuff required by the entire site like css and main images)
    #  - media/ (user-generated content like levels, screenshots, etc.)
    #  - etc/ (history and brian stuff mounted on a volume)
    #  - the tutorials and other pages generated by the static site generator
    massassi-static:
        image: nginx:latest
        hostname: massassi-static
        restart: always
        expose:
            - 8001
        volumes:
            - ./massassi-static/output:/app:ro
            - ./massassi-static/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - massassi-user-data:/massassi-user-data:ro

    # Dynamic parts of massassi, written in python/django and served by 
    # gunicorn
    massassi-django:
        hostname: massassi-django
        build:
            context: ./massassi-django
        restart: always
        expose:
            - 8000
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            MASSASSI_DATABASE_PASSWORD: ${MASSASSI_DATABASE_PASSWORD}
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
            MASSASSI_DATABASE_HOST: ${MASSASSI_DATABASE_HOST}
            SENDGRID_API_KEY: ${SENDGRID_API_KEY}
        volumes:
            - massassi-user-data:/massassi-user-data:rw
            - ./import:/home/brian/code/massassi-django/import

volumes:
    massassi-postgres-data:
    massassi-user-data:
